# Generated by Django 3.0.3 on 2022-03-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=510)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
